// old_modules/dvd-app/src/app/dvd/dvd-new/dvd-new.component.ts
import { Component, OnInit, AfterViewInit, OnDestroy, ViewChild } from '@angular/core';
import { FormGroup, FormControl, Validators, FormBuilder } from '@angular/forms';
import { DvdService } from '../dvd.service';
import { Router } from '@angular/router';
import { OmdbService } from '../omdb.service';
import { FlashMessagesService } from 'angular2-flash-messages';
import { AuthService } from '../../auth/auth.service';

declare var require: any;
const Uppy = require('uppy/lib/core');
const Dashboard = require('uppy/lib/plugins/Dashboard');
const Tus = require('uppy/lib/plugins/Tus');

@Component({
	selector: 'app-dvd-new',
	templateUrl: './dvd-new.component.html',
	styleUrls: ['./dvd-new.component.scss']
})
export class DvdNewComponent implements OnInit, AfterViewInit, OnDestroy {
	newForm: FormGroup;
	@ViewChild('plot') plot;
	plotData: any;
	valueChanges: any;
	private uppy;

	constructor(
		private dvdService: DvdService,
		private router: Router,
		private omdb: OmdbService,
		private fb: FormBuilder,
		private flashMessagesService: FlashMessagesService,
		private authService: AuthService
	) { }

	ngOnInit(): void {
		this.newForm = this.fb.group({
			'primary': this.fb.group({
				'title': new FormControl(null, Validators.required),
				'year': new FormControl(null, Validators.required)
			}),
			'plot': new FormControl(this.plotData, Validators.required)
		})

		this.valueChanges = this.newForm.controls['primary'].valueChanges
			.subscribe(() => {
				const title: FormControl = this.newForm.get('primary.title').value
				const year: FormControl = this.newForm.get('primary.year').value;
				this.omdb.getOmdb(title, year)
					.subscribe(
						(res) => {
							this.plotData = res;
							this.newForm.controls['plot'].patchValue(this.plotData);
					});
			})
	}

	ngAfterViewInit() {
		const fileInputs: HTMLElement[] = Array.from(document.querySelectorAll('input[type=file]'));

		fileInputs.forEach(fileInput => {
			fileInput.style.display = 'none';

			this.uppy = Uppy({
				id: fileInput.id,
				autoProceed: false,
				restrictions: {
					maxFileSize: 3000000000,
					maxNumberOfFiles: 1,
					minNumberOfFiles: 1,
					allowedFileTypes: ['video/*']
				}
			})
				.use(Dashboard, {
					trigger: 'form',
					target: fileInput.parentNode,
					showLinkToFileUploadResult: false,
					inline: true,
					height: 250,
					width: 250
				})
				.use(Tus, {
					endpoint: 'http://moviedatabase-env.us-west-2.elasticbeanstalk.com/files',
					chunkSize: 5 * 1024 * 1024,
					resume: true,
					autoRetry: true,
					retryDelays: [0, 1000, 3000, 5000]
				})
				.run();

				this.uppy.on('upload-success', (file, data) => {
					const uploadedFileData = JSON.stringify({
						id: data.url,
						storage: 'cache',
						metadata: {
							filename:  file.name,
							size:      file.size,
							mime_type: file.type,
							title: this.newForm.get('primary.title').value,
							year: this.newForm.get('primary.year').value,
							plot: this.plotData
						}
					});
					const attachment = JSON.stringify({
						movie: {
							video: {
								id: data.url,
								storage: 'cache',
								metadata: {
									filename:  file.name,
									size:      file.size,
									mime_type: file.type,
									title: this.newForm.get('primary.title').value,
									year: this.newForm.get('primary.year').value,
									plot: this.plotData
								}
							}
						}
					});

					const hiddenInput = document.getElementById('video_data') as HTMLInputElement;
					hiddenInput.value = uploadedFileData;
					hiddenInput.name = attachment;
			});
		});
	}

	ngOnDestroy() {
		this.valueChanges.unsubscribe();
	}

	upload() {
		const video_data = document.getElementById('video_data');

		this.flashMessagesService.show('Your video is being uploaded', { cssClass: 'alert-success', timeout: 5000 })

		this.dvdService.newMovie(
			video_data.getAttribute('value'),
			this.newForm.get('primary.title').value,
			this.newForm.get('primary.year').value,
			this.newForm.get('plot').value
		)
			.subscribe(
				() => {
					if (this.dvdService.status === 200) {
						this.flashMessagesService.show('Video upload successful', { cssClass: 'alert-success', timeout: 10000 });
					}
				},
				(error) => {
				 this.flashMessagesService.show('Video upload failed', { cssClass: 'alert-danger', timeout: 10000 });

					let header: number;
					this.dvdService.header.subscribe((value) => header = value);

					if (header === 401) {
						this.router.navigate(['/signin']);
						this.dvdService.header.next(200);
						this.authService.userSignedIn$.next(false);
					}
				}
			)

		this.newForm.reset();
	}
}

<div class="container">
	<h1>Movie Add Form</h1>
	<form [formGroup]="newForm" (ngSubmit)="upload()">
		<div class="form-group" formGroupName="primary">
			<label for="title">Title:</label>
			<input
				type="text"
				name="title"
				class="form-control"
				formControlName="title"
			>

			<label for="year">Year:</label>
			<input
				type="text"
				name="year"
				class="form-control"
				formControlName="year"
			>
		</div>

		<div class="form-group">
			<label for="plot">Plot:</label>
			<textarea
				class="form-control"
				formControlName="plot"
				cols="30"
				rows="10"
				#plot
			>
			</textarea>
		</div>

		<input 
			type="hidden" 
			id="video_data"
		>
		
		<div class="form-group">
			<input 
				type="file" 
				placeholder="Upload file..."
			>
		</div>

		<div class="form-group">
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
	</form>
</div>

// dvd-app/src/containers/DvdNew/DvdNew.jsx
import React, { Component } from 'react';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';

import { withAlert } from 'react-alert';
import Uppy from '@uppy/core';
import Tus from '@uppy/tus';
import { DashboardModal } from '@uppy/react';
import Input from '../../components/UI/Input/Input';
import Tabs from '../../components/Navigation/Tabs/Tabs';
import { checkValidity } from '../../shared/utility';
import * as actions from '../../store/actions/index';


const initialState = {
  newForm: {
    title: {
      elementType: 'input',
      elementConfig: {
        type: 'text',
      },
      value: '',
      name: 'title',
      validation: {
        required: true,
      },
      valid: false,
      touched: false,
    },
    year: {
      elementType: 'input',
      elementConfig: {
        type: 'text',
      },
      value: '',
      name: 'year',
      validation: {
        required: true,
      },
      valid: false,
      touched: false,
    },
    plot: {
      elementType: 'textarea',
      elementConfig: {
        type: '',
        rows: '10',
      },
      value: '',
      name: 'plot',
      validation: {
        required: true,
      },
      valid: false,
      touched: false,
    },
  },
  formIsValid: false,
  modalOpen: false,
};

class DvdNew extends Component {
  constructor(props) {
    super(props);
    const { newForm } = this.state;
    this.videoDataRef = React.createRef();

    this.uppy = Uppy({
      autoProceed: false,
      restrictions: {
        maxFileSize: 3000000000,
        maxNumberOfFiles: 1,
        minNumberOfFiles: 1,
        allowedFileTypes: ['video/*'],
      },
    });

    this.uppy.use(Tus, {
      endpoint: 'http://moviedatabase-env.us-west-2.elasticbeanstalk.com/files',
      chunkSize: 5 * 1024 * 1024,
      resume: true,
      autoRetry: true,
      retryDelays: [0, 1000, 3000, 5000],
    });

    this.uppy.on('complete', (result) => {
      const uploadedFileData = JSON.stringify({
        id: result.successful[0].uploadURL,
        storage: 'cache',
        metadata: {
          filename: result.successful[0].data.name,
          size: result.successful[0].data.size,
          mime_type: result.successful[0].data.type,
          title: newForm.title.value,
          year: newForm.year.value,
          plot: newForm.plot.value,
        },
      });
      const attachment = JSON.stringify({
        movie: {
          video: {
            id: result.successful[0].uploadURL,
            storage: 'cache',
            metadata: {
              filename: result.successful[0].data.name,
              size: result.successful[0].data.size,
              mime_type: result.successful[0].data.type,
              title: newForm.title.value,
              year: newForm.year.value,
              plot: newForm.plot.value,
            },
          },
        },
      });

      const hiddenInput = this.videoDataRef.current;
      hiddenInput.value = uploadedFileData;
      hiddenInput.name = attachment;
    });
  }

  state = { ...initialState };

  static getDerivedStateFromProps = (nextProps, prevState) => ({
    newForm: {
      ...prevState.newForm,
      plot: {
        ...prevState.newForm.plot,
        value: nextProps.omdb,
      },
    },
  });

  submitHandler = (event) => {
    event.preventDefault();
    const { onClearOmdb, onPostMovie } = this.props;
    const { newForm } = this.state;
    const formData = {};

    Object.keys(newForm).forEach((formElementIdentifier) => {
      if (Object.prototype.hasOwnProperty.call(newForm, formElementIdentifier)) {
        formData[formElementIdentifier] = newForm[formElementIdentifier].value;
      }
    });
    formData.video = this.videoDataRef.current.value;

    onPostMovie(formData)
      .then(() => this.showAlert())
      .then(() => {
        this.clearForm();
        onClearOmdb();
      });
  };

  inputChangedHandler = (event, inputIdentifier) => {
    const { newForm } = this.state;
    const { onGetOmdb } = this.props;

    const updatednewForm = {
      ...newForm,
    };

    const updatedFormElement = {
      ...updatednewForm[inputIdentifier],
    };

    updatedFormElement.value = event.target.value;
    updatedFormElement.valid = checkValidity(
      updatedFormElement.value,
      updatedFormElement.validation,
    );
    updatedFormElement.touched = true;
    updatednewForm[inputIdentifier] = updatedFormElement;

    let formIsValid = true;
    Object.keys(updatednewForm).forEach((inputIdent) => {
      if (Object.prototype.hasOwnProperty.call(updatednewForm, inputIdent)) {
        formIsValid = updatednewForm[inputIdent].valid && formIsValid;
      }
    });

    this.setState(prevState => ({
      ...prevState,
      newForm: updatednewForm,
      formIsValid,
    }),
    () => {
      onGetOmdb(newForm.title.value, newForm.year.value);
    });
  };

  modalOpenHandler = () => {
    this.setState({ modalOpen: true });
  };

  modalCloseHandler = () => {
    this.setState({ modalOpen: false });
  };

  componentWillUnmount = () => {
    const { onClearOmdb } = this.props;

    this.clearForm();
    onClearOmdb();
  }

  componentDidMount = () => {
    const { onSetAuthRedirectPath } = this.props;

    onSetAuthRedirectPath('/new');
  };

  preventDefaultAction = (event) => {
    event.preventDefault();
    this.modalOpenHandler();
  };

  showAlert = () => {
    const { error, alert } = this.props;
    const { newForm } = this.state;

    if (error === null || error.length === 0) {
      const alertSuccess = `${newForm.title.value} has been successfully saved`;

      return alert.show(alertSuccess, { type: 'success', timeout: 5000 });
    }

    if (error) {
      Object.keys(error).map(value => alert.show(`${value}: ${error[value]}`, { type: 'error' }));
    }

    return null;
  };

  clearForm = () => {
    this.setState(initialState);
  };

  formSubmissionActions = (event) => {
    event.preventDefault();
    this.submitHandler(event);
  };


  render() {
    const { modalOpen, newForm } = this.state;

    const formElementsArray = [];
    Object.keys(newForm).forEach((key) => {
      if (Object.prototype.hasOwnProperty.call(newForm, key)) {
        formElementsArray.push({
          id: key,
          config: newForm[key],
        });
      }
    });

    const form = formElementsArray.map(formElement => (
      <Input
        key={formElement.id}
        elementType={formElement.config.elementType}
        elementConfig={formElement.config.elementConfig}
        value={formElement.config.value}
        invalid={!formElement.config.valid}
        shouldValidate={formElement.config.validation}
        touched={formElement.config.touched}
        changed={event => this.inputChangedHandler(event, formElement.id)}
        name={formElement.config.name}
        label={formElement.config.name}
        id={formElement.config.id}
      />
    ));

    return (
      <div className="container">
        <Tabs />

        <h4 className="row justify-content-center">Dvd Add Form</h4>
        <form onSubmit={this.formSubmissionActions}>
          { form }

          <input type="hidden" id="video_data" ref={this.videoDataRef} />

          <div className="form-group">
            <button onClick={this.preventDefaultAction} type="button">Select Movie</button>
            <DashboardModal
              uppy={this.uppy}
              open={modalOpen}
              closeModalOnClickOutside
              onRequestClose={this.modalCloseHandler}
            />
          </div>

          <div className="form-group">
            <button className="btn btn-primary" type="submit">Save</button>
          </div>
        </form>
      </div>
    );
  }
}

DvdNew.defaultProps = {
  error: null,
  alert: null,
};

DvdNew.propTypes = {
  onClearOmdb: PropTypes.func.isRequired,
  onPostMovie: PropTypes.func.isRequired,
  onGetOmdb: PropTypes.func.isRequired,
  onSetAuthRedirectPath: PropTypes.func.isRequired,
  error: PropTypes.arrayOf(PropTypes.string),
  alert: PropTypes.shape({
    type: PropTypes.string,
  }),
};

const mapStateToProps = state => ({
  error: state.movie.error,
  omdb: state.omdb.plot,
});

const mapDispatchToProps = dispatch => ({
  onPostMovie: movieData => dispatch(actions.postMovie(movieData)),
  onGetOmdb: (title, year) => dispatch(actions.getOmdb(title, year)),
  onClearOmdb: () => dispatch(actions.clearOmdb()),
  onSetAuthRedirectPath: path => dispatch(actions.setAuthRedirectPath(path)),
});

export default connect(mapStateToProps, mapDispatchToProps)(withAlert(DvdNew));
